import type { Experience, Person } from '../types';

export const experiences: Experience[] = [
  {
    id: 'coffee-passport',
    title: 'Coffee Passport',
    location: 'North Park, San Diego',
    schedule: 'Saturday · 10:00 AM',
    description: 'Explore a different local café each month while meeting people who enjoy an easy conversation.',
    members: 48,
    category: 'Food & coffee',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
    host: 'Sarah',
    hostMembership: 'contributor',
  },
  {
    id: 'sunrise-club',
    title: 'Sunrise Club',
    location: 'Mission Bay, San Diego',
    schedule: 'Sunday · 6:30 AM',
    description: 'Start the morning with a relaxed walk, thoughtful conversation, and no performance pressure.',
    members: 31,
    category: 'Outdoors',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    host: 'Keoni',
    hostMembership: 'partner',
  },
  {
    id: 'weekend-adventures',
    title: 'Weekend Adventures',
    location: 'San Diego County',
    schedule: 'Twice monthly',
    description: 'Try something new with a small group, from neighborhood walks to low-key day trips.',
    members: 42,
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?auto=format&fit=crop&w=1200&q=80',
    host: 'Mia',
    hostMembership: 'member',
  },
];

export const people: Person[] = [
  { id: '1', name: 'Meaghan', city: 'San Diego', membership: 'contributor', bio: 'Coffee, community, and thoughtful experiences.' },
  { id: '2', name: 'Emily', city: 'San Diego', membership: 'member', bio: 'Bookstores, beach walks, and local food.' },
  { id: '3', name: 'Kai', city: 'Honolulu', membership: 'partner', bio: 'Creative host and weekend explorer.' },
];

export const memberships = [
  {
    name: 'Community',
    key: 'community',
    monthly: 'Free',
    enrollment: 'No enrollment fee',
    bestFor: 'Exploring MISNÖ',
    description: 'Start with the public community and discover where you want to participate.',
    features: ['Community profile', 'Public experiences and events', 'Public circles and conversations', 'Passport timeline', 'Upgrade anytime'],
    cta: 'Join free',
  },
  {
    name: 'Member',
    key: 'member',
    monthly: '$30',
    enrollment: '$50 one-time enrollment',
    bestFor: 'Deeper member access',
    description: 'Support the community while receiving custom benefits and optional rewards.',
    features: ['Everything in Community', 'One custom Pi', 'Behind-the-scenes access', 'Always Open Access', '20% merchandise earnings (optional)', '30% Pi referral rewards (optional)'],
    cta: 'Become a Member',
  },
  {
    name: 'Contributor',
    key: 'contributor',
    monthly: '$40',
    enrollment: '$100 one-time enrollment',
    bestFor: 'Hosting and contributing',
    description: 'Help shape conversations, creative work, and community experiences.',
    features: ['Everything in Member', 'Two custom Pi', 'Co-host community sessions', 'Late-entry guest privilege', 'Exclusive Inner Circle', 'Founder-selected T-shirt', '40% merchandise earnings (optional)', '50% Pi referral rewards (optional)'],
    cta: 'Become a Contributor',
    badge: 'Most popular',
  },
  {
    name: 'Partner',
    key: 'partner',
    monthly: '$60',
    enrollment: '$150 one-time enrollment',
    bestFor: 'Building with MISNÖ',
    description: 'Take a larger role in shaping the direction and future of the community.',
    features: ['Everything in Contributor', 'Three custom Pi', 'Co-host access', 'Exclusive Inner Circle', 'Personalized T-shirt and hoodie', 'Two monthly reinstatement passes', '50% merchandise earnings (optional)', '70% Pi referral rewards (optional)'],
    cta: 'Become a Partner',
  },
  {
    name: 'Executive Partner',
    key: 'executive',
    monthly: '$100',
    enrollment: '$600 one-time enrollment',
    bestFor: 'Community leadership',
    description: 'The highest level for people committed to representing and growing MISNÖ.',
    features: ['Everything in Partner', 'Unlimited jersey customization', 'Featured merchandise collection', 'Official co-host privileges', 'Three personalized merchandise items', '$25 monthly stipend for eligible term', '60% merchandise earnings (optional)', '80% Pi referral rewards (optional)'],
    cta: 'Apply for Executive',
    badge: 'Application required',
  },
] as const;
