import { ArrowRight, MessageCircle, Radio, Users } from 'lucide-react';
import { Button } from '../../components/Button';
import { Card } from '../../components/Card';
import { ExperienceCard } from '../../components/ExperienceCard';
import { MembershipCard } from '../../components/MembershipCard';
import { openSignup } from '../../lib/auth';
import { experiences, memberships } from '../../lib/data';

export function HomePage() {
  return <>
    <section className="section-space"><div className="page-container grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">Real people. Shared experiences.</p><h1 className="display-title mt-5 max-w-3xl">Find people you’ll actually want to spend time with.</h1><p className="mt-6 max-w-xl body-muted">Discover experiences, join thoughtful communities, and build a Passport full of moments that happened beyond the screen.</p><Button onClick={openSignup} className="mt-8">Join free <ArrowRight className="ml-2 h-4 w-4" /></Button></div><Card className="p-6 sm:p-8"><p className="text-sm font-medium">What’s happening tonight</p><div className="mt-6 divide-y divide-border"><div className="flex gap-4 py-4"><Radio className="mt-1 h-5 w-5 text-forest"/><div><p className="font-semibold">Coffee & Conversation</p><p className="mt-1 text-sm text-muted">Live room · 18 people</p></div></div><div className="flex gap-4 py-4"><Users className="mt-1 h-5 w-5 text-forest"/><div><p className="font-semibold">North Park Food Walk</p><p className="mt-1 text-sm text-muted">Tomorrow · 12 going</p></div></div><div className="flex gap-4 py-4"><MessageCircle className="mt-1 h-5 w-5 text-forest"/><div><p className="font-semibold">What should we try next?</p><p className="mt-1 text-sm text-muted">Active in Coffee Passport</p></div></div></div></Card></div></section>
    <section id="experiences" className="section-space border-y border-border bg-surface"><div className="page-container"><p className="eyebrow">Featured experiences</p><div className="mt-4 flex items-end justify-between gap-5"><div><h2 className="section-title">Start with something you already enjoy.</h2><p className="mt-3 body-muted">Experiences bring the people, conversations, rooms, and meetups together.</p></div></div><div className="mt-10 grid gap-5 md:grid-cols-3">{experiences.map(e=><ExperienceCard key={e.id} experience={e}/>)}</div></div></section>
    <section id="memberships" className="section-space"><div className="page-container"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Memberships</p><h2 className="section-title mt-4">Start free. Grow as you become more involved.</h2><p className="mt-4 body-muted">Membership represents contribution, not status.</p></div><div className="mt-10 space-y-5"><MembershipCard plan={memberships[0]} wide/><div className="grid gap-5 md:grid-cols-2"><MembershipCard plan={memberships[1]}/><MembershipCard plan={memberships[2]}/></div><div className="grid gap-5 md:grid-cols-2"><MembershipCard plan={memberships[3]}/><MembershipCard plan={memberships[4]}/></div></div></div></section>
    <section className="section-space border-t border-border bg-surface"><div className="page-container grid gap-10 md:grid-cols-3"><div><span className="text-sm font-semibold">01</span><h3 className="mt-4 text-xl font-semibold">Discover</h3><p className="mt-3 body-muted">Find experiences, neighborhoods, circles, and people.</p></div><div><span className="text-sm font-semibold">02</span><h3 className="mt-4 text-xl font-semibold">Participate</h3><p className="mt-3 body-muted">Join the conversation, attend a meetup, or enter a room.</p></div><div><span className="text-sm font-semibold">03</span><h3 className="mt-4 text-xl font-semibold">Contribute</h3><p className="mt-3 body-muted">Earn access to Workspace and help create the community.</p></div></div></section>
  </>;
}
